<?php use Aura\Html\Escaper as e; ?>
<?php use Llvdl\Responder\Common\Form; ?>
<?php /** @var Llvdl\Domain\Match $match */ ?>
<!DOCTYPE html>
<html>
    <head>
        <title>My first match</title>
        <?php include __DIR__ . '/_headers.phtml'; ?>
    </head>
    <body
        <?php if ($currentAccount): ?>data-current-account="<?php print e::a($currentAccount->getId()); ?>"<?php endif; ?>
        data-match-id="<?php print e::a($match->getId()); ?>"
        >
        <div class="container">
            <?php include __DIR__ . '/_account.phtml'; ?>
            <?php include __DIR__ . '/_messages.phtml'; ?>
            <div class="jumbotron">
                <h1>
                    Match details
                    - <span class="name"><?php print e::h($match->getName()); ?></span>
                    <small>
                        (<span class="match-id"><?php print e::h($match->getId()); ?>)</span>
                    </small>
                </h1>
            </div>

            <p v-if="loaded &amp;&amp; match.state == 'new'">Match has not been started.</p>
            <p v-if="loaded &amp;&amp; match.state == 'in_progress'" class="state">Match is in progress.</p>

            <form role="form" method="post" id="players" v-if="match" v-bind:class="{ loaded: loaded }">
                <p v-for="(account, number) in match.players">
                    Player {{number}}:
                    <span v-if="account" v-bind:class="['seat-' + number]">
                        {{account.name}}
                        <span v-if="match.state == 'new' &amp;&amp; currentAccountId &amp;&amp; account.id === currentAccountId">
                            <button class="btn btn-default" name="leave" v-bind:value="number">Leave</button>
                        </span>
                    </span>
                    <span v-else="" v-bind:class="['seat-' + number]">
                        <button v-if="match.state == 'new'" name="join" v-bind:value="number" v-bind:class="{btn: true, 'btn-default': true, disabled: !loggedIn}" v-bind:disabled="!loggedIn">Join</button>
                    </span>
                </p>
                <p v-if="match.state == 'new'">
                    <button name="start" v-bind:class="{btn: true, 'btn-primary': true, disabled: !match.can_start}" v-bind:disabled="!match.can_start">Start</button>
                </p>
            </form>
        </div>

        <script src="/js/match-detail.js"></script>
    </body>
</html>
